jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Running Build/Test"
          command: |
            echo "Starting long-running process..."
            # Simulate your build or test suite
            sleep 120

workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only:
                - main
                - /gh-readonly-queue\/.*/
